[package]
name = "rec"
version = "0.1.0"
authors = ["Rômulo Collopy <romulocollopy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.1"
jack = "0.6.5"
